<?php
  return array (
  'code' => '0000',
  'message' => NULL,
  'content' => 
  array (
    'order_info' => 
    array (
      'rmb_shipping_fee' => 0.0,
      'delivery_address' => 
      array (
        'address_detail' => ',',
        'door_number' => '',
        'receiver' => '',
        'city' => '',
        'phone' => '',
        'road' => '',
        'post_code' => '',
      ),
      'receiver_address_country_code' => NULL,
      'receiver_email' => NULL,
      'outer_shipper_id' => NULL,
      'order_time' => '2026-05-27 16:00:29',
      'buyer_id' => NULL,
      'distributor_info' => NULL,
      'm_coupon_discount' => 0.0,
      'order_status' => 13,
      'buyer_mobile' => '18591771804',
      'trade_id' => '159518846050',
      'in_stock_time' => NULL,
      'outer_user_id' => NULL,
      'use_large_amount_coupon' => false,
      'custom_declares' => 
      array (
        0 => 
        array (
          'outer_sku_id' => '4897148560390*3',
          'total_shipping_fee' => 0.0,
          'declare_unit_price' => 199.0,
          'num' => 1,
          'sub_code' => NULL,
          'payment' => 199.0,
          'total_reduced_amount' => 0.0,
          'product_title' => 'JOYHOVO 辅酶Q10软胶囊（新）',
          'total_tax_fee' => 0.0,
          'total_taxable_amount' => 199.0,
        ),
      ),
      'pickup_info' => NULL,
      'payment' => 199.0,
      'recommend_logistics_code' => NULL,
      'region_discount' => 0.0,
      'customs_clearance_success_time' => NULL,
      'integral_discount' => 0.0,
      'seller_id' => '寰球之家',
      'customs_clearance_status' => NULL,
      'cancel_time' => '2026-05-27 17:24:02',
      'rmb_region_discount' => 0.0,
      'payment_terminal' => NULL,
      'rmb_amount' => 199.0,
      'seller_memo' => NULL,
      'paid_time' => '2026-05-27 16:00:37',
      'wait_in_stock' => false,
      'tariff_fee' => 0.0,
      'shipping_fee' => 0.0,
      'buyer_remark' => '',
      'prescription_info' => NULL,
      'custom_info' => 
      array (
        'ecommerce_platform_name' => '上海海鲲网络科技有限公司',
        'customs_order_no' => '100014426050',
        'pay_company_name' => '连连银通电子支付有限公司',
        'ecommerce_platform_code' => '31049609EX',
        'pay_company_code' => '3301960QY9',
      ),
      'outer_order_source' => 'WeixinMp',
      'order_items_info' => 
      array (
        0 => 
        array (
          'rmb_shipping_fee' => 0.0,
          'num' => 1,
          'second_catalog_id' => 1369,
          'tax_rate' => 0.0,
          'm_coupon_discount' => 0.0,
          'custom_declare' => 
          array (
            'outer_sku_id' => '4897148560390*3',
            'total_shipping_fee' => 0.0,
            'declare_unit_price' => 199.0,
            'num' => 1,
            'sub_code' => NULL,
            'payment' => 199.0,
            'total_reduced_amount' => 0.0,
            'product_title' => 'JOYHOVO 辅酶Q10软胶囊（新）',
            'total_tax_fee' => 0.0,
            'total_taxable_amount' => 199.0,
          ),
          'delivery_type' => 666,
          'ext_data' => NULL,
          'price' => 199.0,
          'product_id' => 'p100617168',
          'support_no_reason_refund' => false,
          'parent_sku_id' => NULL,
          'vendor_price' => 0,
          'payment' => 199.0,
          'region_discount' => 0.0,
          'integral_discount' => 0.0,
          'outer_sku_id' => '4897148560390*3',
          'rmb_region_discount' => 0.0,
          'inside_products' => NULL,
          'refund_status' => 2,
          'refund_type' => 1,
          'first_catalog_name' => '其他分类',
          'tariff_fee' => 0.0,
          'brand_name' => NULL,
          'sku_id' => 'c538142919',
          'sku_properties_name' => '规格:拍一发三',
          'refund_id' => 'TH260527004674401',
          'product_title' => 'JOYHOVO 辅酶Q10软胶囊（新）',
          'brand_id' => 0,
          'order_item_id' => '100014426050000',
          'shipping_fee' => 0.0,
          'third_catalog_name' => '其他分类',
          'product_border' => 1,
          'refund_num' => 1,
          'customs_tax_fee' => NULL,
          'first_catalog_id' => 1368,
          'order_id' => 100014426050,
          'm_adjust_discount' => 0.0,
          'rmb_tax_fee' => 0.0,
          'parent_outer_sku_num' => NULL,
          'tax_fee' => 0.0,
          'shipper_price' => 0,
          'relation_product_infos' => NULL,
          'record_no' => '4897148560390',
          'rmb_m_adjust_discount' => 0.0,
          'refund_amount' => 199.0,
          'third_catalog_id' => 1370,
          'sale_tax_fee' => 0.0,
          'free_freight' => false,
          'taxable_amount' => 199.0,
          'prsc_url' => NULL,
          'max_valid_time' => NULL,
          'rmb_price' => 199.0,
          'sub_codes' => NULL,
          'rmb_m_coupon_discount' => 0.0,
          'outer_refund_biz_no' => NULL,
          'rmb_integral_discount' => 0.0,
          'rmb_m_promotion_discount' => 0.0,
          'pay_tax_coupon_discount' => 0,
          'second_catalog_name' => '其他分类',
          'valid_time' => NULL,
          'parent_outer_sku_id' => NULL,
          'm_promotion_discount' => 0.0,
        ),
      ),
      'rmb_payment' => 199.0,
      'user_id' => 641976050,
      'flight_info' => NULL,
      'delivery_info' => NULL,
      'distributor_id' => 641654519,
      'id_cards' => 
      array (
        0 => 
        array (
          'receiver_id_type' => 1,
          'id_card_check_result' => NULL,
          'receiver_id_no' => '610321199907073113',
          'receiver_name' => '张秦',
        ),
      ),
      'priority_deliver_flag' => false,
      'shipper_name' => NULL,
      'order_id' => 100014426050,
      'receiver_oaid' => NULL,
      'payment_order_no' => '26052716002984982',
      'm_adjust_discount' => 0.0,
      'express_service_name' => NULL,
      'rmb_tax_fee' => 0.0,
      'warehouse_code' => '102387',
      'outer_param' => NULL,
      'payment_currency' => 'CNY',
      'receiver_state' => NULL,
      'tax_fee' => 0.0,
      'update_time' => '2026-05-27 17:24:02',
      'receipted_time' => NULL,
      'receiver_zip' => '410102',
      'payment_transaction_no' => '2026052719389515',
      'seller_role' => 3,
      'rmb_m_adjust_discount' => 0.0,
      'express_service' => false,
      'receiver_name' => '张秦',
      'pay_type' => 'LLZF',
      'sale_tax_fee' => 0.0,
      'accept_time' => '2026-05-27 16:01:31',
      'express_service_code' => NULL,
      'shipping_time' => NULL,
      'payment_company' => 'WeiXin',
      'member_id' => 'HY202511071648236226',
      'store_code' => NULL,
      'amount' => 199.0,
      'pre_sale_delivery_promise_time' => NULL,
      'pickup_in_stores' => false,
      'total_customs_tax_fee' => 0,
      'agent_mobile' => '',
      'rmb_m_coupon_discount' => 0.0,
      'outer_payment_id' => '2026052719389515',
      'distributor_mobile' => '13838026596',
      'receiver_mobile' => '13838026596',
      'member_level' => '0001',
      'recommend_logistics_name' => NULL,
      'rmb_integral_discount' => 0.0,
      'rmb_m_promotion_discount' => 0.0,
      'receiver_address_type' => 0,
      'outer_biz_no' => NULL,
      'receiver_address' => '河南省,郑州市,中原区,红莲街2号',
      'shipper_id' => NULL,
      'receiver_phone' => '13838026596',
      'm_promotion_discount' => 0.0,
      'warehouse_id' => 102387,
    ),
  ),
);